### ISSUE TITLE
re-enable Netlify integration for kubernetes-sigs/kind

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/org#681]
### Organization or repository
kubernetes-sigs/kind

### Name of integration
Netlify

### Link to integration website

https://netlify.com

### Describe what is attempting to be accomplished

Automated build and preview triggering for kind.sigs.k8s.io

### Additional context for request

This was previously enabled in https://github.com/kubernetes/org/issues/397, but now does not appear in integrations in the repo settings and automated builds / previews have stopped, despite being configured on the Netlify end.

**Comment by dims** [comment]
+1

**Comment by nikhita** [comment]
Done. Can you recheck?

**Comment by BenTheElder** [comment]
thanks @nikhita but it still doesn't seem to be enabled:
- doesn't show up in https://github.com/kubernetes-sigs/kind/settings/installations
- netlify.com seems to still be asking me to install it
- new PR does not seem to have a netlify preview status https://github.com/kubernetes-sigs/kind/pull/428

**Comment by nikhita** [comment]
ah gotcha... https://github.com/kubernetes-sigs/kind/settings/installations should have it now.

**Comment by BenTheElder** [comment]
thanks! still trying to figure out why the previews are still down :confused:

**Comment by BenTheElder** [comment]
"Automatically build deploy previews for all pull requests" is definitely on for https://app.netlify.com/sites/k8s-kind/settings/deploys, https://app.netlify.com/sites/k8s-kind/overview still shows "install the github app" but i'm not sure if that's accurate anyhow

**Comment by BenTheElder** [comment]
cc @zacharysarah, any ideas? :confused:

**Comment by BenTheElder** [comment]
looks like the last preview was `Fri, Mar 29, 2019 at 2:57 AM`, sometime since then all automated builds just stopped !?

**Comment by zacharysarah** [comment]
@BenTheElder I'm looking now--I notice that yeah, preview deployments seem to have halted, but also that there are no outbound notifications configured. I'm tweaking a couple of settings now, will update when I know more.

**Comment by BenTheElder** [comment]
OK so what I did was link the netlify site to the netlify-test repo and then back to the kind repo.

Per @zacharysarah's conversation with netlify support, they only use deploy keys over SSH to clone, seems setting up the github app does that.

It now finally doesn't ask me to install the app on the netlify site, and previews are working. :tada: 


I suspect kubebuilder was similarly broken on the 29th, @mrbobbytables pointed out this is when the netlify-test was setup.

https://github.com/kubernetes-sigs/kubebuilder/pull/657 <-- 2 day old PR, no netlify status
https://github.com/kubernetes-sigs/kubebuilder/pull/644 <-- 12 day old PR, netlify status

**Comment by BenTheElder** [comment]
FYI @pwittrock @mengqiy for kubebuilder you may need to go through the above process to re-enable automated netlify deploys ^

**Comment by mrbobbytables** [comment]
I'm curious if this was triggered by requesting the integration of their new "Native GitHub App" whereas previous ones were done with the "OAuth App authentication".

**Comment by mengqiy** [comment]
@BenTheElder Thanks for headup! Let me fix it.

**Comment by cblecker** [comment]
This looks like it's working. Can you confirm?

**Comment by mengqiy** [comment]
@cblecker I confirm it's working for kubebuilder.

**Comment by mengqiy** [comment]
@Liujingfang1 You may need to do the same thing for `kubectl book` as mentioned in https://github.com/kubernetes/org/issues/681#issuecomment-479671856

**Comment by BenTheElder** [comment]
this is working, thank you all!!
